"""empty message

Revision ID: 001
Revises: 
Create Date: 2025-03-13 22:52:30.106485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('confirm_email', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('user_email_confirm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('send_date', sa.DateTime(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('confirm_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_email_confirm_id'), 'user_email_confirm', ['id'], unique=False)
    op.create_table('lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('audio_file_source', sa.String(length=255), nullable=True),
    sa.Column('audio_file_translate', sa.String(length=255), nullable=True),
    sa.Column('text_source', sa.Text(), nullable=True),
    sa.Column('text_translate', sa.Text(), nullable=True),
    sa.Column('split_text_source', sa.Text(), nullable=True),
    sa.Column('split_text_translate', sa.Text(), nullable=True),
    sa.Column('split_audio_source', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('split_audio_translate', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('draft', sa.Boolean(), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['lesson.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_lesson_id'), 'lesson', ['id'], unique=False)
    op.create_table('content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('field', sa.String(length=20), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('file', sa.String(length=255), nullable=True),
    sa.Column('text_source', sa.Text(), nullable=True),
    sa.Column('split_text_source', sa.Text(), nullable=True),
    sa.Column('split_text_translate', sa.Text(), nullable=True),
    sa.Column('split_audio_source', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('split_audio_translate', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('poster', sa.String(length=255), nullable=True),
    sa.Column('thumbnails', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_id'), 'content', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_id'), table_name='content')
    op.drop_table('content')
    op.drop_index(op.f('ix_lesson_id'), table_name='lesson')
    op.drop_table('lesson')
    op.drop_index(op.f('ix_user_email_confirm_id'), table_name='user_email_confirm')
    op.drop_table('user_email_confirm')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
