"""empty message

Revision ID: 002
Revises: 001
Create Date: 2025-03-19 21:46:00.464256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('split_data_source', sa.JSON(), nullable=True))
    op.add_column('lesson', sa.Column('split_data_translate', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson', 'split_data_translate')
    op.drop_column('lesson', 'split_data_source')
    # ### end Alembic commands ###
